### ISSUE TITLE
Issue #02 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [M8825/Villow#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
1. ~~Hey Malkhaz, for your User Auth MVP, that should unofficially include your Splash Page as that will offer your users a chance to Sign Up or Login. I would also make a note that on unsuccessful sign up or login, errors will be rendered.~~
2. Your four Main Features' bullets are a bit sparse as of now and I'd like to see more thought on these. I can provide an example. Currently, your Google Maps feature lists that you'll be implementing the Google Maps. What I'd expect to see is more along the lines of:
+ Seeded homes will be rendered on Google Map API element. 
+ User will be able to interact with the API to pull up a home's show modal and zoom in and out of the map.
+ User will not be required to sign in/up before using the Map feature.
Hope this gives a better idea.
3. ~~Also, your estimated time is putting your work at 11 days (with Render Hosting and Production README). We have roughly 14 official days to work on this project, so I would reallocate to estimated time for Listings and the Google Map API maybe.~~

**Comment by M8825** [comment]
1. Done!
2. DONE?
3. Done!

**Comment by keginzburg** [comment]
Awesome work here!
