### ISSUE TITLE
Issue #03 - Database Schema

### ISSUE THREAD

**Issue by keginzburg** [M8825/Villow#3]
# Database Schema
- [x] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Formatting wise, be sure to add a title of "Postgres Database Schema" above your database schema. Additionally, be sure to use backticks (`) to make your column names and foreign keys shaded. For example:
*  "id" should be `id`
* "index on username, unique: true" should be "index on `username, unique: true`"
2. You've used `bigint` data types for a lot of columns that should be `integer`. `bigint` is mostly reserved for id and foreign key columns. Be sure to change that.
3. Should your listings' `air_cond` and `parking` columns be booleans?
4. In your favorites table, you should probably change your `owner_id` column to a `favoriter_id`. The user this foreign key refers to should be the user who favorited the listing, not the listing's owner. This makes more sense semantically.

Please let me know once you've made these corrections/additions. Thanks!

**Comment by M8825** [comment]
1. DONE

2. DONE

3. DONE: 

    - On Zillow, I have seen three possible options for `:air_cond` and `:parking`. A listing may have it - `true` - or not - `false` - and sometimes data is not given `"No data"`; Therefore, I think the `.string` column data type is more appropriate than the `boolean`; Please, correct me if I'm wrong. 

4. DONE

**Comment by keginzburg** [comment]
Looks good!

As for the boolean data types for `air_cond` and `parking`, that's interesting. You could always opt for true or false and the possible null value if not data is given. But I will leave this up to you. Otherwise, great work!
