### ISSUE TITLE
Issue #03 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [M8825/Villow#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. Looks solid! My only concern is that you should not reveal your users' `session_token` or `password_digest` within your frontend state. Nix those please, then feel free to close this issue.

**Comment by M8825** [comment]
- DONE
